### ISSUE TITLE
Identifier le système d'OAuth2

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#1]
Identifier le système à utiliser. Documenter ça dans une page wiki. 

Critères d'acceptation: 
- arriver avec un système d'authentification OAuth2 compatible avec Song et Score.

Requis: Supporte oAuth2, OpenID connect (google, Linkedin, Facebook). Supporte LDAP. Touters les applications entres elles utilisent des tokens.

**Comment by steptek** [comment]
We do have checking for an oAuth solution to secure the APIs which fit best our requirement.
my findings on this topic are:
 - Actually the solutions bench-marking was related to four or five providers.
 - We do have a requirement that the chosen provider should be acting as Identity provider and at least giving out of the box a branching adapters for external providers for ID management (Ldap, social..).
 - We do prefer using a pre-built and ready to use software and not developing our own from scratch
 - The listed solutions are:
    + Auth0: very known and robust solution, offres till 7K users on his free plan, over that it needs a different plan. (Json and schema configuration based, also offers an admin console)
    + CAS: Central authentication service: robust and multi modules, fit well on multi component architecture  (Administration and maintainability effort is High)
    + Ping: offers openId system on split components (Sso federate, ID services...), some basic components are included on his free plan, for more an other plan is needed.
   + Keycloak:  RH Jboss solution, act as an Authentication and authorization provider, offers flexible authentication ways (granting type: credential, password, authorization code...)
(Administration and maintainability effort is High,  console over-configuration can be confusing, SSL/TLS hand checking is necessary, multi-endpoints could also be confusing).
  + Spring  security: managed by spring oAuth2 ecosystem, auto-configuration based (Metadata annotations, Yaml files), offers authentification using external ID providers, and his own authorization system, java coding oriented on the top of spring rest or boot frameworks.

As of this analyse and investigation and taking on account the preference suggested for keycloak by the product owner. we set up an instance of keycloak server (up and running) on the openstack collaboratory available at http://cr-ste-justine.xyz/ .

Nag.

**Comment by aalex** [comment]
J'ai créé une page wiki pour stocker ces infos: https://github.com/cr-ste-justine/wiki/wiki/Credentials-system
