### ISSUE TITLE
Page liste patients + barre de facettes

### ISSUE THREAD

**Issue by Emma-Drieux** [cr-ste-justine/clin-project#100]
Implementer:
- [ ] L'ecran liste mode défaut
- [ ] L'ecran liste + barre de recherche état active (focus state)
- [ ] L'ecran liste + facette recherche état active

Selon les maquette de Lucas

**Comment by nyanofthemoon** [comment]
Blocked until the design is final.

**Comment by nyanofthemoon** [comment]
@vferretti We discussed that perhaps we would do "request" page rather than a "patient search"... so I moved it to backlog.

**Comment by luclemo** [comment]
> We discussed that perhaps we would do "request" page rather than a "patient search"

@nyanofthemoon Not sure I understand what this means...?
