### ISSUE TITLE
Créer un compte d'usager

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#11]
En tant que coordonnateur, je dois pouvoir créer un compte d'usager

Critères d'acceptance: 
- informations requises: prénom, nom, courriel;
- Peut se faire dans l'interface d'un autre logiciel, tel que Keycloak;
- documenter les procédures

**Comment by steptek** [comment]
Configuration S.G.A pour le coordonnateur est faite, et ce dernier a un access on R.W sur le Realm ayant les utilisateurs (Usagers.)

**Comment by aalex** [comment]
Documentation technique seulement, pour le moment.

**Comment by aalex** [comment]
Voici la page wiki vers la doc:
https://github.com/cr-ste-justine/clin-project/wiki/S.G.A
