### ISSUE TITLE
[CLIN-VAR] GeneResultsTable - Paginated Data

### ISSUE THREAD

**Issue by nyanofthemoon** [cr-ste-justine/clin-project#133]
In CLIN-VAR (Patient Variant Interpretor)

![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/d5e64676-15c0-4ab7-a5ae-9a5056e18a13)

For the active (or selected query):
- [ ] Map data from `clin-proxy-api` to table columns in Gene tab
- [ ] Paginate results

**Comment by latch2112** [comment]
Investigating Parent-Child to solve feature
