### ISSUE TITLE
[CLIN-VAR] Map Generic Filters to ES

### ISSUE THREAD

**Issue by nyanofthemoon** [cr-ste-justine/clin-project#137]
In CLIN-VAR (Patient Variant Interpretor):

- [x] Translate the categories by ids in locales in `clin-frontend`
- [x] Translate the filter by ids in locales in `clin-frontend`
- [x] Add Generic filters in `schema.json` in `clin-proxy-api`
   - [x] Categorie: Variants
     - [x] Type de variant
     - [x] Conséquence
     - [x] Références externe
     - [x] Impact clinique (clinvar)
     - [x] Chromosome 
   - [x] Categorie: Génomique
     - [x] Type de gène
     - [x] Ensembles de gènes non-HPO
     - [x] RadboudUMC
     - [x] Autres ensemble de gènes 
   - [x] Categorie: Prédictions in-silico
     - [x] VEP
     - [x] SIFT
     - [x] Polyphen
     - [x] LRT
     - [x] MutationAssessor
     - [x] FATHMM
  - [x] Categorie: Zygosité et Analyse Familiale
     - [x] Transmission

https://balsamiq-wireframes.appspot.com/?state=%7B%22ids%22:%5B%221WjcEGAgdGmPrLgF4oNf4YFBwYehQbQWX%22%5D,%22action%22:%22open%22,%22userId%22:%22110047922525123122063%22%7D

**Comment by nyanofthemoon** [comment]
@vferretti @latch2112 Here is the list of remaining Generic filters to map. We need some help with the ElasticSearch mappings to complete this task.

**Comment by latch2112** [comment]
reference externe-dbsnp : "bdExt.dbSNP"
reference externe-pubmed : "bdExt.pubmed"
reference externe-orphanet : "bdExt.orphanet"
reference externe-omim : "bdExt.omim.keyword"  
reference externe-clinvar : "clinvar.clinvar_id"

autre ensemble de gene et NON-HPO
"autre ensemble de gene non hpo-radboudumc" : "genes.radboudumc"
"autre ensemble de gene non hpo-orphanet" : "genes.orphanet"
"autre ensemble de gene non hpo-ensembl" : "genes.ensemblId"

Categorie: Prédictions in-silico
vep : consequences.impact
"FATHMM" : "consequences.predictions.FATHMM"
"SIFT" : "consequences.predictions.SIFT"
"LRT" : "consequences.predictions.LRT_pred"
 "MutationAssessor" : "consequences.predictions.MutationAssessor_pred"
"Polyphen2_HDIV" : "consequences.predictions.Polyphen2_HDIV"
"Polyphen2_HVAR" : "consequences.predictions.Polyphen2_HVAR_pred"

**Comment by latch2112** [comment]
et on rajoute .keyword pour les aggrégations
