### ISSUE TITLE
[CLIN-VAR] Enable NumericalComparison Filters

### ISSUE THREAD

**Issue by nyanofthemoon** [cr-ste-justine/clin-project#142]
In CLIN-VAR (Patient Variant Interpretor)

- [ ] Implement in `schema.json` the mappings for facets:
  - [x] VEP? @latch2112 **NO**
  - [x] GERP  **NO**
  - [x] PhastCons   **NO**
  - [x] PhyloP   **YES**

https://balsamiq-wireframes.appspot.com/?state={%22action%22:%22open%22,%22ids%22:[%221WjcEGAgdGmPrLgF4oNf4YFBwYehQbQWX%22],%22userId%22:%22110047922525123122063%22}#

=== Implement these as single filters and not grouped filters for now ===
Under 'Cohorte' (from wireframe); the following one also is only numerical comparison filter:
 - [ ] Implement in `schema.json` the mappings for facets:
  - [x]  gnomAD_exomes; Population de contrôle (quantité d'allèles; nombre total d'allèle; fréquence de l'allèle)  
  - [x] gnomAD_genome; Population de contrôle (quantité d'allèles; nombre total d'allèle; fréquence de l'allèle)
  - [x] ExAc; Population de contrôle (quantité d'allèles; nombre total d'allèle; fréquence de l'allèle)
  - [x] 1000Gp3; Population de contrôle (quantité d'allèles; nombre total d'allèle; fréquence de l'allèle)

**Comment by latch2112** [comment]
For GERP:
{ "range" : { "consequences.conservationsScores.GERP": { "gte" : "0.45" }}}

**Comment by latch2112** [comment]
GERP is out :(

**Comment by latch2112** [comment]
will come back with details with the rest of them...

**Comment by latch2112** [comment]
PhyloP17Way:   consequences.conservationsScores.PhyloP17Way    value 0.29708

**Comment by latch2112** [comment]
type range dans ElasticSearch
AC = Allele Count -- Compte des allèles alternatives (entier; long)
AF = Allele Frequencies -- Fréquence allélique (numérique; float)
HC = Homozygote count -- Nombre d'homozygote (entier; long)
AN = Allele Number -- Nombre d'allèle totale (alternative et de référence) 
--- gnomAD_exomes
frequencies.gnomAD_exomes.AC 
frequencies.gnomAD_exomes.AF
--- gnomAD_genomes
frequencies.gnomAD_genomes.AC
frequencies.gnomAD_genomes.AF
--- ExAc
frequencies.ExAc.AC
frequencies.ExAc.AF
--- Uk10k
frequencies.Uk10k.AC
frequencies.Uk10k.AF
--- 1000Gp3
frequencies.1000Gp3.AC
frequencies.1000Gp3.AF
--- Cohorte interne
frequencies.interne.AC
frequencies.interne.AF
frequencies.interne.HC
frequencies.interne.AN
--- Cohorte laboXYZ (i.e. CRSJ, ICM, etc...) 
frequencies.laboCRSJ.AC
frequencies.laboCRSJ.AF
frequencies.laboCRSJ.HC
frequencies.laboCRSJ.AN
