### ISSUE TITLE
[CLIN-VAR] Enable Composite Filters

### ISSUE THREAD

**Issue by nyanofthemoon** [cr-ste-justine/clin-project#149]
In CLIN-VAR (Patient Variant Interpretor)

- [ ] Implement in `schema.json` the mappings for facets:
  - [x] CADD
  - [x] revel
...?

https://balsamiq-wireframes.appspot.com/?state={%22action%22:%22open%22,%22ids%22:[%221WjcEGAgdGmPrLgF4oNf4YFBwYehQbQWX%22],%22userId%22:%22110047922525123122063%22}#

=== Implement these as single filters and not grouped filters for now ===

**Comment by nyanofthemoon** [comment]
@latch2112 Need information for these please!

**Comment by latch2112** [comment]
consequences.predictions: {
        "FATHMM": "T", "FATHMM_score": 0.04852,
        "Polyphen2_HVAR_pred": "B", "Polyphen2_HVAR_score": 0.22909,
        "LRT_pred": "N", "LRT_score": 0.28882,
        "SIFT": "D", "SIFT_score": 0.50676,
        "DANN_score": 0.81984,
        "CADD_score": 0.32584,
        "REVEL_score": 0.22036,
      }
