### ISSUE TITLE
Produire le workflow de séquencement d'un exome

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#16]
En tant que bio informaticien, je veux pouvoir rouler un workflow sur un exome qui me permettra d'avoir les variants call format (VCF) annotés.

Critères:
- les données fournies par la bioinformaticienne

Tâches:
- [x]  fastqc report
- [x] ajouter illumina BED
- [x] docker pour snpEff

**Comment by latch2112** [comment]
- [ ] test

**Comment by latch2112** [comment]
Validation du résultat d'annotation de de l'alignement à faire
Documentation à faire

**Comment by aalex** [comment]
https://github.com/cr-ste-justine/chujs-alignment-workflow/commits/dev
