### ISSUE TITLE
[TI-CLIN] Resize column breaks table

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#173]
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/99c72bda-76a3-4981-a300-a67bc25cda98)

Problem: resizing column makes other columns disappear. Columns re-appear when user moves mouse

**Comment by nyanofthemoon** [comment]
https://github.com/palantir/blueprint/issues/3833
