### ISSUE TITLE
[TI-CLIN] First "data column" should stay pinned on horizontal scroll

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#174]
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/e6cad296-0924-45a7-85c0-ef7199632b24)

**Comment by luclemo** [comment]
@nyanofthemoon Hmmm, am I missing something? Looks like it's still only the number column that is fixed. This may be my fault if I was not clear enough 😓. By "first data column" I mean the first _after_ the numbers col. See screenshot above better visual example.

**Comment by nyanofthemoon** [comment]
Fix the fat border :)

![image](https://user-images.githubusercontent.com/3919995/69743461-7812d000-110c-11ea-8bc5-7540349e456f.png)

**Comment by luclemo** [comment]
@claudia1296 @nyanofthemoon I played with this in the inspector and found a solution by applying a `::before` pseudo-element to the first _non-fixed_ column cells.

The part I need to leave up to you is how to dynamically move these styles based on the column position.

Here's the CSS:
```
.bp3-table-cell.bp3-table-truncated-cell.bp3-table-cell-row-4.bp3-table-cell-col-1.bp3-table-cell-ledger-even::before {
    content: '';
    display: block;
    height: 100%;
    position: absolute;
    left: 0;
    box-shadow: 0px 0px 8px 1px rgba(16, 22, 26, 0.5);
}
```

Here's the browser screenshot:

![image](https://user-images.githubusercontent.com/1451515/69826651-145ad680-11e2-11ea-8b7d-83fb328f7525.png)
