### ISSUE TITLE
[TI-CLIN] Hide placeholder on active inputs

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#177]
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/50daf518-037f-4c97-ba7c-610a47904a55)
Once cursor is activate in input, placeholder should not appear. This should be true for all inputs globally.
![image](https://user-images.githubusercontent.com/1451515/69554662-187fbd80-0f70-11ea-9472-043154499ac4.png)

**Comment by nyanofthemoon** [comment]
@luclemo Core functionality of AntD. Not easily "overridable". What do?

**Comment by nyanofthemoon** [comment]
Will try using CSS ```input:focus::placeholder{
       color:transparent;
  }```

**Comment by nyanofthemoon** [comment]
Only work for Input components and not Autocomplete/Search

**Comment by luclemo** [comment]
Hmmm, ok if that's default AntD settings and tough to override, perhaps in that case we can make the placeholder text a bit lighter as in the design specs: `rgba(35, 55, 80, 0.38)`...?
