### ISSUE TITLE
[TI-CLIN] Using columns filter removes too many columns

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#178]
This seems to be related to issue #173

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/ddf674fc-029c-4703-9d36-e8d67fa63191)

**Comment by nyanofthemoon** [comment]
Fixed with PR for https://github.com/cr-ste-justine/clin-project/issues/173

**Comment by luclemo** [comment]
@nyanofthemoon I think this is now a new problem related to this maybe? 👉 #187

**Comment by luclemo** [comment]
@nyanofthemoon New opposite issue: columns filter removes no columns 😅
![image](https://user-images.githubusercontent.com/1451515/69760004-609a0e00-1131-11ea-912d-45f3004f47b3.png)
