### ISSUE TITLE
[ClinVar] Results from variant quick search bar are disabled

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#181]
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/68d4b1a0-1801-4de4-ba86-3983d2121c36)
User cannot make a selection

**Comment by nyanofthemoon** [comment]
@luclemo What should be the behavior of the selection? There are 2 use cases:
Filter category and filter value.

**Comment by nyanofthemoon** [comment]
Related to https://github.com/cr-ste-justine/clin-project/issues/134
