### ISSUE TITLE
Investigate: Image to text processing library

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#19]
- [x] Define the library to convert PDF to text. 
- [x] pouvoir traiter un lot de fichiers PDF (10) specified in command-line (analyse de performance)

**Comment by aalex** [comment]
Il va falloir la découper en plus petites. C'est une ongoing. It's a carry-on story.

**Comment by aalex** [comment]
The Python library is pytesseract. The info has been put here: https://github.com/cr-ste-justine/wiki/wiki/PDF-Search

**Comment by steptek** [comment]
We demoed the extraction of the content from KF data portal pdfs using a prototyping project (Python) with listed libraries:  Pillow, tesseract ...
This story defines a prototyping solution to prouve the concept and the usage of mentioned libraries.
The prototype will be used to start up clin project java based, doing portal searching for pdf contents.
Nag

**Comment by aalex** [comment]
Here it is: https://github.com/cr-ste-justine/clin-prototypes/blob/master/pdf_to_text.py
