### ISSUE TITLE
[TI-CLIN] Columns should expand to fill available space

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#192]
- Columns should expand
- Drop shadow on first column should only be visible if there is overflow content (scroll)
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/2312b144-b4ae-4893-8e54-59ec067d58fe)

**Comment by nyanofthemoon** [comment]
@luclemo I think we did this already on QA?
