### ISSUE TITLE
[TI-CLIN] Let user click outside of column to deselect

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#193]
Currently if I click on a column there is no way to set its state back to unselected.
![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/80fcf245-da29-406b-bb36-0ca969392bf0)

**Comment by luclemo** [comment]
Same issue applies to cells :)

**Comment by latch2112** [comment]
@luclemo Donc...  il y a moyen de dé-sélectionner en cliquant sur:

- filtrer:
![image](https://user-images.githubusercontent.com/965232/83552103-3d348f00-a4d7-11ea-92b1-0ddf233858a5.png)
- entrer du texte dans le autocomplete:
![image](https://user-images.githubusercontent.com/965232/83552218-66edb600-a4d7-11ea-9400-dd66cb7e3f51.png)
- Organizer ou Afficher
![image](https://user-images.githubusercontent.com/965232/83552329-943a6400-a4d7-11ea-8b05-bbde4feefac5.png)

Peut-être que c'est un effet secondaire non planifié ou pas...
Quoi qu'il en soit, je peux essayer de retirer la sélection en cliquant sur la 'zone' en dehors du tableau direct (autour du tableau) en capturant un évènement mais sinon je sais pas comment le faire autrement
Qu'est-ce que tu en penses?

**Comment by latch2112** [comment]
@luclemo Il n'y a pas de façon facile pour faire ce que tu demandes.  

Mettre un button ou du texte qui mentionne 'dé-sélectionner' serait à mon avis le plus simple.

C'est comme dans Google spreadsheet, il n'y a pas moyen de dé-sélectionner une cellule ou un ensemble de ceux-ci, ça reviens toujours à une sélection.

La façon complexe est de capturer tous les évènements à partir du parent et d'intercepter les bons (pour que le bouton exporter continue à fonctionner) 
Par contre, faire cela reviens à écrire une tonne de code spaghetti avec des callbacks du parents au enfants et des enfants au parent...  En React, c'est normalement juste dans une seule direction (props drill down)

**Comment by luclemo** [comment]
Pas prioritaire. On ne fait pas.
