### ISSUE TITLE
Recherche de patients: Recherche par nom d’étude ne fonctionne pas

### ISSUE THREAD

**Issue by vferretti** [cr-ste-justine/clin-project#198]
- Taper Rapidomix dans la boîte de recherche. 
- BUG: Ne retourne aucun résultat ce qui n’est pas normal. Beaucoup de patients appartiennent à cette étude

**Comment by latch2112** [comment]
![image.png](https://images.zenhubusercontent.com/5c59d5e107cc4d6f39e559e4/4d6c9411-da33-4460-80c5-a80912bc16ab)

**Comment by vferretti** [comment]
mon erreur, je pensais que ca prenais un x à la fin
