### ISSUE TITLE
Définir le modèle de données de SONG

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#2]
En tant que bioinfo, je désire importer les données cliniques et metadonnées dans le nouveau système

Critères d'acceptaion:

- [x] Plusieurs fichiers JSON décrivant le format des informations à importer. 
- [x] Fichier tableur décrivant ce qu'il y a dans chaque champ.
- [x] Définir les sources de données pour populer SONG et établir les règles de transformation entre les données sources et le modèle SONG
- [x] Définir les types d'analyses de SONG et leur fichiers associés (les Bundles)
- [x] Documenter l'usage du modèle de song
- [x] Harmoniser le modèle-cible avec le modèle actuel (DB clinic)
- [x] Investiguer si le modèle est à harmoniser avec le modèle actuel (DB clinic)

**Comment by Emma-Drieux** [comment]
[x} Plusieurs fichiers JSON décrivant le format des informations a importer
       Importes dans Github : clin-etl/song_json_schemas
[x} Fichier tableur décrivant ce qu’il y a dans chaque champ:
https://docs.google.com/spreadsheets/d/1pomnuQAysG6wcbhP-f3mg-HTXbQwo5-62ETDHxU6wTo/edit#gid=173601673

[x] Définir les sources de données pour copuler SONG (fichier excel cite precedemment)
[  ] Etablir les régles de transformation entre les données sources et le modèle SONG

[X] Définir les types d’analyses de SONG et leurs fichiers associes: note par ailleur en remarque dans les onglets d'analyse.json et file.json:
Pour un donneur, on aura dans le fond trois types d'analyses auxquelles on rattachera des fichiers: sequencing_read avec bam et bam.bai, variant_call avec vfc et vcf filtre, et rapport avec fichier excel (il faudra donc rajouter un nouveau type d'analyse et un novueau type de fichier)

[  ] Documenter l’usage du modelé SONG: reste la portie SCORE
https://docs.google.com/document/d/15dUHQ4ia9JwcaQTTdGIeIXuXQaP-FmY11YO7ZW4kbzI/edit
Il faudra par ailleurs realiser un document simplifie pour les informaticiens

[ ]Harmoniser le modèle cible avec le modèle actuel (BD Clinic)

**Comment by aalex** [comment]
Les schemas Song sont ici: https://github.com/cr-ste-justine/clin-etl/tree/dev/song_json_schemas

**Comment by aalex** [comment]
@Emma-Drieux Reste t-il encore quelques questions, ou puis-je fermer ce ticket?

**Comment by Emma-Drieux** [comment]
@aalex oui tu peux le fermer, les donnees qu'on a choisi ne vont pas change pour le moment

**Comment by aalex** [comment]
SVP valider le format du JSON aussi.

https://github.com/cr-ste-justine/clin-etl/pull/14/files

Pour @latch2112
