### ISSUE TITLE
HIGH: Mettre à jour le profil de l'utilisateur après manipulation des filtres par défaut

### ISSUE THREAD

**Issue by vferretti** [cr-ste-justine/clin-project#201]
Quand on efface un filtre par défaut, on doit s'assurer de mettre à jour le profil de l'utilisateur; Si un filtre n'est pas trouvé, on doit pas planter non plus

**Comment by latch2112** [comment]
@vferretti Pourquoi as-tu fermé ce ticket ?

**Comment by latch2112** [comment]
@FrancisRenaud Est-ce que tu as travaillé sur ce ticket ?

**Comment by nyanofthemoon** [comment]
PR ready to go: https://github.com/cr-ste-justine/clin-frontend/pull/195
