### ISSUE TITLE
Recherche par gène: implementer la requête ElasticSearch

### ISSUE THREAD

**Issue by vferretti** [cr-ste-justine/clin-project#222]
La recherche se fait sur **la liste complète des gènes possible** qu’on a dans notre DB qui est toujours la même pour tous les patients. 

Autrement dit elle ne doit pas se faire sur la liste des gènes avec mutations pour un patient donné. Il se pourrait qu’une requête donne un résultat nul si le gène n’est pas muté pour un patient donné. 

Ranking:
Le score d’un match est plus grand selon le type de terme qu’il matche. Par exemple si le match est dans Gene Symbol, le résultat doit retourner en premier. L’ordre d’importance est le suivant:
- Gene symbol - Colonne = Symbol: 
- Gene Aliases - Colonne Synonyms
- Gene Ensembl ID - Colonne = Other_designations, champ Ensembl
- Gene name - Colonne Full_name_from_nomenclature_authority
- OMIM ID - Colonne = Other_designations, champ MIN
- HGNC ID - Colonne = Other_designations, champ HGNC
- NCBI Gene ID - Colonne GeneID

On retourne et affichera seulement les 5 premiers résultats. 

Lorsqu’on sélectionne un gène, le critère est ajouté à la requête active de la page de recherche de variants et la liste des variants se rafraîchit.

On peut ajouter plusieurs gène dans la requête. On a alors un OU entre les gènes. Comme dans cet exemple du portail de ICGC:

![image](https://user-images.githubusercontent.com/1181124/77765358-88807c00-7014-11ea-9bb7-0889929680db.png)

**Comment by latch2112** [comment]
{
  "size": 5, 
  "query": {
    "bool": {
      "should": [
        {
          "multi_match": {
            "query": "braf",
            "fields": [
              "geneSymbol^7",
              "alias^6",
              "ensemblId^5",
              "name^4",
              "omim^3",
              "hgnc^2",
              "geneId"
              ]
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}

**Comment by latch2112** [comment]
Validation svp...
`{
  "took" : 18,
  "timed_out" : false,
  "_shards" : {
    "total" : 4,
    "successful" : 4,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 63.15361,
    "hits" : [
      {
        "_index" : "genes_test",
        "_type" : "_doc",
        "_id" : "ENSG00000157764",
        "_score" : 63.15361,
        "_source" : {
          "ensemblId" : "ENSG00000157764",
          "hgnc" : "1097",
          "hpo" : [
            "Scoliosis (HP:0002650)",
            "Sensorineural hearing impairment (HP:0000407)",
            "Shield chest (HP:0000914)",
            "Intracranial cystic lesion (HP:0010576)",
            "Radial deviation of finger (HP:0009466)",
            "Anterior creases of earlobe (HP:0009908)",
            "Skin nodule (HP:0200036)",
            "Central adrenal insufficiency (HP:0011734)",
            "Feeding difficulties in infancy (HP:0008872)",
            "Reduced factor XIII activity (HP:0008357)",
            "Abnormal pulmonary valve morphology (HP:0001641)",
            "Hypertonia (HP:0001276)",
            "Generalized hypotonia (HP:0001290)",
            "Downslanted palpebral fissures (HP:0000494)",
            "Lymphedema (HP:0001004)",
            "Nasogastric tube feeding in infancy (HP:0011470)",
            "Delayed puberty (HP:0000823)",
            "Wide nasal bridge (HP:0000431)",
            "Global developmental delay (HP:0001263)",
            "Macrocephaly (HP:0000256)",
            "Redundant skin (HP:0001582)",
            "Myelodysplasia (HP:0002863)",
            "Vertigo (HP:0002321)",
            "EEG abnormality (HP:0002353)",
            "Superior pectus carinatum (HP:0000917)",
            "Abnormality of the frontal bone (HP:0430000)",
            "Dental malocclusion (HP:0000689)",
            "Optic atrophy (HP:0000648)",
            "Wide intermamillary distance (HP:0006610)",
            "Slow-growing hair (HP:0002217)",
            "Recurrent infections (HP:0002719)",
            "Spina bifida occulta (HP:0003298)",
            "Deep palmar crease (HP:0006191)",
            "Excessive daytime somnolence (HP:0001262)",
            "Severe sensorineural hearing impairment (HP:0008625)",
            "Relative macrocephaly (HP:0004482)",
            "Brachydactyly (HP:0001156)",
            "Radioulnar synostosis (HP:0002974)",
            "Hypogonadism (HP:0000135)",
            "Hyperkeratosis (HP:0000962)",
            "Ventricular septal defect (HP:0001629)",
            "Progressive visual field defects (HP:0007987)",
            "Sudden loss of visual acuity (HP:0001117)",
            "Postnatal growth retardation (HP:0008897)",
            "Somatic mutation (HP:0001428)",
            "Epicanthus (HP:0000286)",
            "Multiple lentigines (HP:0001003)",
            "Dolichocephaly (HP:0000268)",
            "Curly hair (HP:0002212)",
            "Multiple cafe-au-lait spots (HP:0007565)",
            "Oculomotor apraxia (HP:0000657)",
            "Alveolar cell carcinoma (HP:0006519)",
            "Thickened helices (HP:0000391)",
            "Impaired oropharyngeal swallow response (HP:0031162)",
            "Dysarthria (HP:0001260)",
            "Neoplasm of the anterior pituitary (HP:0011750)",
            "Thickened nuchal skin fold (HP:0000474)",
            "Gastroesophageal reflux (HP:0002020)",
            "Increased circulating prolactin concentration (HP:0000870)",
            "Neurofibrosarcoma (HP:0100697)",
            "Long face (HP:0000276)",
            "Fine hair (HP:0002213)",
            "Keratosis pilaris (HP:0032152)",
            "Large earlobe (HP:0009748)",
            "Excessive wrinkled skin (HP:0007392)",
            "Brachycephaly (HP:0000248)",
            "Bronchogenic cyst (HP:0100730)",
            "High forehead (HP:0000348)",
            "Dysphagia (HP:0002015)",
            "Abnormality of the dentition (HP:0000164)",
            "Dilatation (HP:0002617)",
            "Increased intracranial pressure (HP:0002516)",
            "Vomiting (HP:0002013)",
            "Webbed neck (HP:0000465)",
            "Freckling (HP:0001480)",
            "Hearing impairment (HP:0000365)",
            "Hypoplasia of the frontal lobes (HP:0007333)",
            "Abnormal bleeding (HP:0001892)",
            "Short neck (HP:0000470)",
            "Synovitis (HP:0100769)",
            "Abnormality of the voice (HP:0001608)",
            "Pectus carinatum (HP:0000768)",
            "Scapular winging (HP:0003691)",
            "Cystic hygroma (HP:0000476)",
            "Neonatal hypotonia (HP:0001319)",
            "Osteolysis (HP:0002797)",
            "Pectus excavatum (HP:0000767)",
            "High palate (HP:0000218)",
            "Sleep apnea (HP:0010535)",
            "Cavernous hemangioma (HP:0001048)",
            "Patent ductus arteriosus (HP:0001643)",
            "Abnormality of the pulmonary artery (HP:0004414)",
            "Nystagmus (HP:0000639)",
            "Intellectual disability (HP:0001256)",
            "Hypoplasia of the zygomatic bone (HP:0010669)",
            "Prominent forehead (HP:0011220)",
            "Bulbous nose (HP:0000414)",
            "Cubitus valgus (HP:0002967)",
            "Abnormal hair quantity (HP:0011362)",
            "Posteriorly rotated ears (HP:0000358)",
            "Myopia (HP:0000545)",
            "Lentigo maligna melanoma (HP:0012059)",
            "Bundle branch block (HP:0011710)",
            "Nausea and vomiting (HP:0002017)",
            "Abnormal heart valve morphology (HP:0001654)",
            "Brittle hair (HP:0002299)",
            "Amegakaryocytic thrombocytopenia (HP:0004859)",
            "Deep philtrum (HP:0002002)",
            "Mitral valve prolapse (HP:0001634)",
            "Type II diabetes mellitus (HP:0005978)",
            "Dystrophic fingernails (HP:0008391)",
            "Male infertility (HP:0003251)",
            "Midface retrusion (HP:0011800)",
            "Multiple plantar creases (HP:0008113)",
            "Myocardial infarction (HP:0001658)",
            "Generalized hyperpigmentation (HP:0007440)",
            "Open mouth (HP:0000194)",
            "Ichthyosis (HP:0008064)",
            "Slow decrease in visual acuity (HP:0007924)",
            "Genu valgum (HP:0002857)",
            "Peripheral axonal neuropathy (HP:0003477)",
            "Long palpebral fissure (HP:0000637)",
            "Hyperextensible skin (HP:0000974)",
            "Autosomal dominant inheritance (HP:0000006)",
            "Biparietal narrowing (HP:0004422)",
            "Obesity (HP:0001513)",
            "Anteverted nares (HP:0000463)",
            "Hyperhidrosis (HP:0000975)",
            "Optic nerve dysplasia (HP:0001093)",
            "Aplasia of the semicircular canal (HP:0011381)",
            "Hyperpigmentation of the skin (HP:0000953)",
            "Cerebral ischemia (HP:0002637)",
            "Open bite (HP:0010807)",
            "Seizures (HP:0001250)",
            "Intrauterine growth retardation (HP:0001511)",
            "Strabismus (HP:0000486)",
            "High (HP:0002705)",
            "Cognitive impairment (HP:0100543)",
            "Hepatomegaly (HP:0002240)",
            "Abnormal mitral valve morphology (HP:0001633)",
            "Progressive visual loss (HP:0000529)",
            "Headache (HP:0002315)",
            "Hypospadias (HP:0000047)",
            "Low posterior hairline (HP:0002162)",
            "Melanocytic nevus (HP:0000995)",
            "Abnormal platelet function (HP:0011869)",
            "Retinopathy (HP:0000488)",
            "Numerous nevi (HP:0001054)",
            "Submucous cleft hard palate (HP:0000176)",
            "Kyphoscoliosis (HP:0002751)",
            "Low-set ears (HP:0000369)",
            "Enlarged thorax (HP:0100625)",
            "Neoplasm (HP:0002664)",
            "Triangular face (HP:0000325)",
            "Micrognathia (HP:0000347)",
            "Hydronephrosis (HP:0000126)",
            "Sparse hair (HP:0008070)",
            "Full cheeks (HP:0000293)",
            "Polyhydramnios (HP:0001561)",
            "Abnormal endocardium morphology (HP:0004306)",
            "Low-set (HP:0000368)",
            "Tongue thrusting (HP:0100703)",
            "Muscular hypotonia (HP:0001252)",
            "Osteopenia (HP:0000938)",
            "Splenomegaly (HP:0001744)",
            "Intellectual disability (HP:0001249)",
            "Hypertelorism (HP:0000316)",
            "Hypertrophic cardiomyopathy (HP:0001639)",
            "Depressed nasal bridge (HP:0005280)",
            "Papule (HP:0200034)",
            "Polyphagia (HP:0002591)",
            "Abnormal visual field test (HP:0030588)",
            "Heterogeneous (HP:0001425)",
            "Cerebral calcification (HP:0002514)",
            "Underdeveloped supraorbital ridges (HP:0009891)",
            "Short stature (HP:0004322)",
            "Autosomal recessive inheritance (HP:0000007)",
            "Constipation (HP:0002019)",
            "Functional abnormality of the gastrointestinal tract (HP:0012719)",
            "Absent eyebrow (HP:0002223)",
            "Delayed skeletal maturation (HP:0002750)",
            "Dry skin (HP:0000958)",
            "Sparse or absent eyelashes (HP:0200102)",
            "Atrial septal defect (HP:0001631)",
            "Multiple palmar creases (HP:0006114)",
            "Abnormal aortic valve morphology (HP:0001646)",
            "Abnormal localization of kidney (HP:0100542)",
            "Central diabetes insipidus (HP:0000863)",
            "Thick vermilion border (HP:0012471)",
            "Macrotia (HP:0000400)",
            "Aplasia/Hypoplasia of the abdominal wall musculature (HP:0010318)",
            "Failure to thrive (HP:0001508)",
            "Palpebral thickening (HP:0030939)",
            "Arrhythmia (HP:0011675)",
            "Tetralogy of Fallot (HP:0001636)",
            "Enlarged pituitary gland (HP:0012505)",
            "Abnormality of the chin (HP:0000306)",
            "Hyperextensibility of the finger joints (HP:0001187)",
            "Proportionate short stature (HP:0003508)",
            "Pulmonic stenosis (HP:0001642)",
            "Premature birth (HP:0001622)",
            "Joint hypermobility (HP:0001382)",
            "Reduced factor XII activity (HP:0004841)",
            "Long philtrum (HP:0000343)",
            "Joint hyperflexibility (HP:0005692)",
            "Abnormal dermatoglyphics (HP:0007477)",
            "Narrow forehead (HP:0000341)",
            "Clinodactyly of the 5th finger (HP:0004209)",
            "Bitemporal hemianopia (HP:0030521)",
            "Melanoma (HP:0002861)",
            "Coarctation of aorta (HP:0001680)",
            "Frontal bossing (HP:0002007)",
            "Hypogonadotrophic hypogonadism (HP:0000044)",
            "Abnormality of the ulna (HP:0002997)",
            "Pulmonary artery stenosis (HP:0004415)",
            "Abnormality of the spleen (HP:0001743)",
            "Pectus excavatum of inferior sternum (HP:0000915)",
            "Proptosis (HP:0000520)",
            "Aplasia/Hypoplasia of the eyebrow (HP:0100840)",
            "Muscle weakness (HP:0001324)",
            "Sprengel anomaly (HP:0000912)",
            "Coma (HP:0001259)",
            "Cerebral cortical atrophy (HP:0002120)",
            "Congenital onset (HP:0003577)",
            "Abnormality of vision (HP:0000504)",
            "Abnormal hypothalamus morphology (HP:0012286)",
            "Hypomelanotic macule (HP:0009719)",
            "Large for gestational age (HP:0001520)",
            "Clinodactyly (HP:0030084)",
            "Absent eyelashes (HP:0000561)",
            "Atopic dermatitis (HP:0001047)",
            "Pituitary hypothyroidism (HP:0008245)",
            "Thick lower lip vermilion (HP:0000179)",
            "Atrioventricular canal defect (HP:0006695)",
            "Short nose (HP:0003196)",
            "Papilledema (HP:0001085)",
            "Decreased fertility (HP:0000144)",
            "Abnormality of the nasal bone (HP:0010939)",
            "Cryptorchidism (HP:0000028)",
            "Subcutaneous nodule (HP:0001482)",
            "Ptosis (HP:0000508)",
            "Aplasia/Hypoplasia of the corpus callosum (HP:0007370)",
            "Coarse facial features (HP:0000280)",
            "Hydrocephalus (HP:0000238)",
            "Coarse hair (HP:0002208)",
            "Abnormality of coagulation (HP:0001928)",
            "Neuroblastoma (HP:0003006)",
            "Increased susceptibility to fractures (HP:0002659)",
            "Abnormality of the vertebral column (HP:0000925)",
            "Palmoplantar keratoderma (HP:0000982)",
            "Failure to thrive in infancy (HP:0001531)",
            "Poor suck (HP:0002033)",
            "Abnormal esophagus morphology (HP:0002031)"
          ],
          "variants" : [
            "chr7:g.140721690T>A",
            "chr7:g.140726457A>G",
            "chr7:g.140753848C>A",
            "chr7:g.140776448A>G",
            "chr7:g.140801026G>T",
            "chr7:g.140801879G>A",
            "chr7:g.140802035G>T",
            "chr7:g.140835075CTA>C"
          ],
          "geneSymbol" : "BRAF",
          "geneId" : "673",
          "omim" : [
            "164757"
          ],
          "name" : "B-Raf proto-oncogene, serine/threonine kinase",
          "donors" : [ ],
          "orphanet" : [
            {
              "dataId" : "22214",
              "panel" : "Selection of therapeutic option in colorectal cancer (Orph:357194)"
            },
            {
              "dataId" : "28071",
              "panel" : "Selection of therapeutic option in melanoma (Orph:544260)"
            },
            {
              "dataId" : "19660",
              "panel" : "Pilomyxoid astrocytoma (Orph:251615)"
            },
            {
              "dataId" : "905",
              "panel" : "Differentiated thyroid carcinoma (Orph:146)"
            },
            {
              "dataId" : "1559",
              "panel" : "Cardiofaciocutaneous syndrome (Orph:1340)"
            },
            {
              "dataId" : "3768",
              "panel" : "Langerhans cell histiocytosis (Orph:389)"
            },
            {
              "dataId" : "1032",
              "panel" : "Noonan syndrome with multiple lentigines (Orph:500)"
            },
            {
              "dataId" : "206",
              "panel" : "Noonan syndrome (Orph:648)"
            },
            {
              "dataId" : "22213",
              "panel" : "Selection of therapeutic option in non-small cell lung carcinoma (Orph:357191)"
            },
            {
              "dataId" : "10756",
              "panel" : "Craniopharyngioma (Orph:54595)"
            },
            {
              "dataId" : "10778",
              "panel" : "Classic hairy cell leukemia (Orph:58017)"
            }
          ],
          "alias" : [
            "NS7",
            "RAFB1",
            "BRAF1",
            "Braf"
          ],
          "location" : "7q34",
          "frequencies" : [ ],
          "radboudumc" : [
            "Intelectual Disability (Rad:Intelectual Disability)",
            "Hearth (Rad:Hearth)",
            "Short Stature And Skeletal Dysplasia (Rad:Short Stature And Skeletal Dysplasia)",
            "Hemostatic/Thrombotic (Rad:Hemostatic/Thrombotic)",
            "Mendeloime Gene (Rad:Mendeloime Gene)",
            "Hereditary Cancer (Rad:Hereditary Cancer)",
            "Skin Disorders (Rad:Skin Disorders)"
          ]
        }
      },
      {
        "_index" : "genes_test",
        "_type" : "_doc",
        "_id" : "ENSG00000278910",
        "_score" : 30.174187,
        "_source" : {
          "ensemblId" : "ENSG00000278910",
          "hgnc" : "43877",
          "geneId" : "100885775",
          "name" : "BRAF-activated non-protein coding RNA",
          "donors" : [ ],
          "alias" : [
            "LINC00586"
          ],
          "location" : "9q21.11-q21.12",
          "variants" : [ ],
          "geneSymbol" : "BANCR",
          "frequencies" : [ ]
        }
      }
    ]
  }
}`

**Comment by latch2112** [comment]
après discussion sur Slack, voici la nouvelle requête:
`{
  "size": 5,
  "_source": [
    "geneSymbol",
    "alias",
    "ensemblId",
    "name",
    "omim",
    "hgnc",
    "geneId"
    ],
  "query": {
    "bool": {
      "should": [
        {
          "multi_match": {
            "query": "braf kras",
            "fields": [
              "geneSymbol^7",
              "alias^6",
              "ensemblId^5",
              "name^4",
              "omim^3",
              "hgnc^2",
              "geneId"
              ]
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}`
et voici le nouveau résultat:
`{
  "took" : 40,
  "timed_out" : false,
  "_shards" : {
    "total" : 4,
    "successful" : 4,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 4,
    "max_score" : 63.521774,
    "hits" : [
      {
        "_index" : "genes_test",
        "_type" : "_doc",
        "_id" : "ENSG00000157764",
        "_score" : 63.521774,
        "_source" : {
          "ensemblId" : "ENSG00000157764",
          "hgnc" : "1097",
          "geneId" : "673",
          "omim" : [
            "164757"
          ],
          "name" : "B-Raf proto-oncogene, serine/threonine kinase",
          "alias" : [
            "NS7",
            "RAFB1",
            "BRAF1",
            "Braf"
          ],
          "geneSymbol" : "BRAF"
        }
      },
      {
        "_index" : "genes_test",
        "_type" : "_doc",
        "_id" : "ENSG00000133703",
        "_score" : 63.50282,
        "_source" : {
          "ensemblId" : "ENSG00000133703",
          "hgnc" : "6407",
          "geneId" : "3845",
          "omim" : [
            "190070"
          ],
          "name" : "KRAS proto-oncogene, GTPase",
          "alias" : [
            "RALD",
            "NS",
            "KIRAS",
            "RASK2",
            "CFC2",
            "cKiras2",
            "NS3",
            "CKRAS",
            "KRAS2B",
            "KRAS2A",
            "KRAS4B",
            "KRas",
            "KRAS4A",
            "OES",
            "KRAS2",
            "KRAS1"
          ],
          "geneSymbol" : "KRAS"
        }
      },
      {
        "_index" : "genes_test",
        "_type" : "_doc",
        "_id" : "ENSG00000278910",
        "_score" : 30.174187,
        "_source" : {
          "ensemblId" : "ENSG00000278910",
          "hgnc" : "43877",
          "geneId" : "100885775",
          "name" : "BRAF-activated non-protein coding RNA",
          "alias" : [
            "LINC00586"
          ],
          "geneSymbol" : "BANCR"
        }
      },
      {
        "_index" : "genes_test",
        "_type" : "_doc",
        "_id" : "ENSG00000174775",
        "_score" : 17.142183,
        "_source" : {
          "ensemblId" : "ENSG00000174775",
          "hgnc" : "5173",
          "geneId" : "3265",
          "omim" : [
            "190020"
          ],
          "name" : "HRas proto-oncogene, GTPase",
          "alias" : [
            "cKiras",
            "CBAS/HAS",
            "HAMSV",
            "p21ras",
            "RASK2",
            "HRASIDX",
            "HRAS1",
            "cKras",
            "CTLO",
            "CHRAS",
            "RASH1",
            "CHARAS1",
            "KiRas",
            "KRAS",
            "KRAS2"
          ],
          "geneSymbol" : "HRAS"
        }
      }
    ]
  }
}`
à valider svp

**Comment by vferretti** [comment]
@latch2112  J'imagine que c'est valide. Faudrait tester plus à fond avec plusieurs requêtes

**Comment by latch2112** [comment]
@vferretti 
Voici l'accès à Kibana pour tester à fond plusieurs requêtes...

`ssh -L 5601:localhost:5601 ubuntu@142.1.177.220`
Utilise l'index genes_test

Voici un exemple complet...  il faut entrer les mots clés dans le champs query du 'multi-match'
`GET /genes_test/_search
{
  "size": 5,
  "_source": [
    "geneSymbol",
    "alias",
    "ensemblId",
    "name",
    "omim",
    "hgnc",
    "geneId"
    ],
  "query": {
    "bool": {
      "should": [
        {
          "multi_match": {
            "query": "braf kras",
            "fields": [
              "geneSymbol^7",
              "alias^6",
              "ensemblId^5",
              "name^4",
              "omim^3",
              "hgnc^2",
              "geneId"
              ]
          }
        }
      ],
      "minimum_should_match": 1
    }
  }
}`

**Comment by vferretti** [comment]
@latch2112 
Je vais tester à partir du UI de clin comme d'habitude

**Comment by latch2112** [comment]
@vferretti Comme tu veux, ferme le ticket parce qu'il bloque les autres...
