### ISSUE TITLE
Design Page Patient

### ISSUE THREAD

**Issue by vferretti** [cr-ste-justine/clin-project#226]
#### Resources

- [Figma design file](https://www.figma.com/file/Hvh1kY1o0rzzO89IuOYITP/CLIN---Page-de-patient?node-id=252%3A4586)

**Comment by luclemo** [comment]
@claudia1296 Le design pour les onglets `Patient` et `Clinique` sont prêt pour l'intégration. On attend d'avoir les fichiers d'Éric avant de procéder pour l'intégration l'onglet `Fichier`.
