### ISSUE TITLE
In-app navigation for logged-out user with existing account

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#236]
# Summary

As a logged-out genetician I need to be automatically redirected to a pasted URL after login.

## Scenario

~~- Given I have an existing account and I am **not** logged into the app~~
~~- When I copy/paste a URL into my browser's address bar~~
~~-- And I have necessary permissions to access the content of that page~~
~~- Then I am redirected to the login screen~~
~~-- And I successfully login~~
~~- Then I am redirected to the page I was trying to access~~

_**EDIT**_

- **Given:** I have an existing account and I am **not** logged into the app
- **When:** I copy/paste a URL into my browser's address bar
- **Then:** I am redirected to the login screen and I login successfully
  -  **If:** I am authorized to access the content
      - I am redirected to the page I was trying to access
  - **Else:** I am redirected to the 403 page (#229)

**Comment by luclemo** [comment]
@latch2112 That condition is written in the scenario. Third line.

**Comment by vferretti** [comment]
En fait,  on ne peut pas connaitre les privilèges de l'utilisateur avant qu'il ne se logue. Je reformulerais légèrement le scénario.

Given I have an existing account and I am not logged into the app
- When I copy/paste a URL into my browser's address bar
-  then I am redirected to the login screen
- After successfully login
-- Then I am redirected to the page I was trying to access if I am authorized to access it
-- OR I am redirected to a generic access deny page if I am not authorised to access it 

@luclemo does it make senses?

**Comment by luclemo** [comment]
Parfait pour moi— je vais modifier l'ordre des choses dans le scenario.
Les specs pour la "generic access deny page" (code 403) sont dans le ticket #229

**Comment by latch2112** [comment]
à la troisième ligne, on n'avais pas encore pris en considérations l'authentification d'où la nécessité de la mettre plus bas...

**Comment by luclemo** [comment]
I am hitting a bug here. When I paste a link (ex: `https://clin.cr-ste-justine.xyz/patient/PA14929`) in an incognito window, I get a brief flash of login screen and then the spinner goes forever. 

Screencast: https://recordit.co/Pbj1EQdsR6

**Comment by luclemo** [comment]
This seems related to the bug reported in #229
