### ISSUE TITLE
Peut pas mettre un filtre par défaut

### ISSUE THREAD

**Issue by latch2112** [cr-ste-justine/clin-project#240]
Peut pas mettre un filtre par défaut en cliquant sur l'étoile à coté du titre et aussi dans le menu

**Comment by nyanofthemoon** [comment]
I think ticket #201 (currently under code review) fixes this as well

https://app.zenhub.com/workspaces/clin-sprints-5c59d2c907cc4d6f39e559c2/issues/cr-ste-justine/clin-project/201
