### ISSUE TITLE
Remove flash of login screen during in-app navigation

### ISSUE THREAD

**Issue by luclemo** [cr-ste-justine/clin-project#245]
## Scenario (happy path for in app navigation)

- Given I am logged into the app
- When I type in a URL into my address bar
  - And that URL has content to which I have permission
- Then I am redirected to the given page

@nyanofthemoon my experience testing the Happy Path results in a flash of the login form before reaching the desired URL.

#### Steps to reproduce

- I have `https://clin.cr-ste-justine.xyz/patient/PA14923` in my clipboard
- I log into the app
- I navigate around until I get to any random variant or patient page
- I paste the `https://clin.cr-ste-justine.xyz/patient/PA14923` in my address bar

#### Result 

The app takes me to the login screen for about 1 second before automatically redirecting me to the desired URL

#### Desired outcome

Take me to the desired URL directly

**Comment by nyanofthemoon** [comment]
@luclemo The flash of content of the login screen will be replaced by the loading animation.

**Comment by nyanofthemoon** [comment]
PR https://github.com/cr-ste-justine/clin-frontend/pull/198
