### ISSUE TITLE
Whole Genome Sequencing

### ISSUE THREAD

**Issue by latch2112** [cr-ste-justine/clin-project#26]
En tant que bio informaticien, je veux pouvoir rouler un workflow d'alignement sur un genome entier, dont la librairie est contenu sur deux lignes qui me permettra d'avoir les variants color format (VCF) annotés.

Tâches:
- [ ]  Transférer les fichiers sur l'instance du workflow engine
- [ ] Ajouter et/ou tester la possibilité de travailler avec plusieurs lignes
- [ ] ajouter et/ou tester la possibilité d'obtenir un deep of coverage 

Critère d'acceptance
- obtenir un gVCF annotés
- deep of coverage file

**Comment by aalex** [comment]
Il faudrait probablement créer 3-4 items de backlog qui seraient des tâches, pour la plupart, à partir de cet epic,
