### ISSUE TITLE
Redirection ne fonctionne pas lorsque déconnecté

### ISSUE THREAD

**Issue by vferretti** [cr-ste-justine/clin-project#266]
Terminer votre session ou ouvrir une fenêtre incognito.
Coller https://clin.cr-ste-justine.xyz/variantDetails/8CD46A1A2E47956823E7CB64F16E1F97
Normalement, on devrait être diriger vers la page de login et, une fois logué, obtenir la page du variant correspondant. 
BUG: on obtient le spinner qui tourne sans fin.
Remarque: si lorsqu'on affiche la page de login, le nom de l'utilisateur et le mot de passe est déjà présent par défaut (à cause du browser), alors là, ca marche. Mais si on a un formulaire vide de login (comme c'est toujours le cas dans une fenêtre incognito), ca ne marche pas

**Comment by luclemo** [comment]
@vferretti J'ai déjà reporté celui-ci dans le ticket originale #236 en QA. Je te laisse voir si tu veux le garder séparé.

**Comment by nyanofthemoon** [comment]
PR https://github.com/cr-ste-justine/clin-frontend/pull/214
