### ISSUE TITLE
Ordonner les choromosomes

### ISSUE THREAD

**Issue by Emma-Drieux** [cr-ste-justine/clin-project#337]
### Dans la facette chromosomes
Ordonner les choromosomes de la sorte: du ch1 -->22 dans un ordre croissant, X ensuite Y

![image.png](https://images.zenhubusercontent.com/5dadb279f8e0d70001993615/3d9400e3-e76a-4205-99f3-5dd450af09c7)

**Comment by latch2112** [comment]
Le composant chromosomes est une agrégation elasticsearch de type terms, changer l'ordre autre que par ordre alphabétique ou par quantité demande du post-traitement important; en ce moment, le SQON-mapper ne supporte pas de sorting
Est-ce vraiment important car ça va nécessiter beaucoup de travail
