### ISSUE TITLE
Ameliorer l'affichage du sous-menu Variants-Consequences (filtre liste variants)

### ISSUE THREAD

**Issue by Emma-Drieux** [cr-ste-justine/clin-project#339]
Conséquences: on doit pouvoir selectionner les regions codantes du génome: cf. capture d'écran suivante

![consequences.png](https://images.zenhubusercontent.com/5c5c6036df0733a30555cc4e/2271b477-4c72-4584-bf89-b7b5f4c7fecc):

**Comment by latch2112** [comment]
c'est pas clair...  spécifier plus en détails svp

**Comment by latch2112** [comment]
le résultat qui s'affiche est une agrégation elasticsearch, on as pas de post-traitement; ceci risque de demander une somme de travail importante si l'ordre est différente que par compte ou alphabétique
