### ISSUE TITLE
Définir et documenter le cycle de vie des données (workflow)

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#5]
Document expliquant quelles sont les étapes de vie des données - un tableau avec chaque étape décrite. À préciser. Quand et comment va t-on importer les données? Les données sont produites, puis stockées dans SONG. Quand il y a un changement dans la base de données MySQL clinic, comment et quand réimporte t-on les données? CRUD

A quel moment on veut extraire les données sources? De quelle manière (automatique, manuelle (CLI ou GUI)? Est-qu'il s'agit de changer l'état d'une analyse dans SONG. Quoi faire pour retirer ou modifier une analyse ou un patient?

Quand crée t-on des documents et de l'info?
- le clinicien remplie le formulaire dans PhenoTips
- etc.
- la bio info analyse des séquences donne la liste des variants
- les données seront publiées sur le site web (sera fait par la suite)

Probablement pour @Emma-Drieux 

Acceptance: écrire ça dans un document d'analyse

**Comment by Emma-Drieux** [comment]
Expliquer les étapes de vie des données - un tableau avec chaque étape décrite. 
À préciser:
Quand et comment va t-on importer les données? Les données sont produites, puis stockées dans SONG. Quand il y a un changement dans la base de données MySQL clinic, comment et quand réimporte t-on les données? CRUD

A quel moment on veut extraire les données sources? De quelle manière (automatique, manuelle (CLI ou GUI)? Est-qu'il s'agit de changer l'état d'une analyse dans SONG. Quoi faire pour retirer ou modifier une analyse ou un patient?

Quand crée t-on des documents et de l'info?

    * le clinicien remplie le formulaire dans PhenoTips

    * etc.

    * la bio info analyse des séquences donne la liste des variants

    * les données seront publiées sur le site web (sera fait par la suite)

Acceptance: écrire ça dans un document d'analyse

**Comment by aalex** [comment]
Voir la section "Cycle des données" dans le document "Analyse de clin"
