### ISSUE TITLE
Opération d'extraction des données source

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#51]
Le système de chargement Clin dois extraire les informations des différentes source afin de préparer le téléversement d'une analyse.

Notes: 
- il ne faut pas que les données des patients sorte du CHU. Anonimiser les données, ou créer un jeu de données factices pour le développement logiciel. (selon les lois en vigueur)
- inclue aller chercher le fichier sur le système de partage de fichiers
- les données sources ne sont pas harmonisées
- la nomenclature des fichiers est non-triviale

Anonimiser: (à compléter)
- nom, prénom, 
- MRN du patient
- date de naissance
- MRN des parents

### Critères d'acceptance
  - vérifiant l'existence du fichier BAM et BAI
  - calculer la taille du fichier BAM et BAI
  - calculer la somme de contrôle du fichier BAM et BAI
  - obtenir les informations de la base de données BV
  - liste des champs à anonimiser

**Comment by Emma-Drieux** [comment]
Pour extraction de la base de donnees de Virginie (pour une analyse type sequencing_read), on doit specifier l'Id_sample et l'Id_Run

**Comment by steptek** [comment]
sampleSubmitterId: utilisee pour extraire depuis la bd-V, et sera auto-générer  pour le payload SONG.
donorSubmitterId: correspond au Mrn patient (auto-générer)
lastName
firstName
birthDate
motherId
fatherId
childId

**Comment by aalex** [comment]
Le code est dans le projet clin-etl, dans la branche feature/payload.

https://github.com/cr-ste-justine/clin-etl/tree/feature/payloads/clin-loader-cli
