### ISSUE TITLE
Authentification à l'API Clin

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#56]
En tant que bioinformaticien, je dois pouvoir m'authentifier via l'interface web.

#### Tâches backend
- commencer un squelette de projet backend
- s'authentifier avec le serveur de SSO (single sign-on Keycloak)
- définition des ressources et endpoints (Web service)
- retourner le jeton OAuth2

### Tâches front-end
- se connecter à l'API avec les credentials
- obtenir le jeton

### Critères d'acceptance
- tenir compte de la sécurité
- liste des méthodes du Web service et de leurs arguments
- S'authentifier avec  email, password

#### Livrables
- document sur l'API

Voir aussi #57

**Comment by aalex** [comment]
On a déjà un exemple de code JS pour obtenir le jeton.

**Comment by nyanofthemoon** [comment]
> On a déjà un exemple de code JS pour obtenir le jeton.
@aalex On ne peut pas l'utiliser, il ne s'applique pas.

**Comment by nyanofthemoon** [comment]
@latch2112 ACL : https://github.com/cr-ste-justine/clin-project/wiki/Clin-Proxy-Api-%3A-Technical-Specifications

**Comment by nyanofthemoon** [comment]
@aalex Code review completed. Awaiting PO review.
