### ISSUE TITLE
Rédaction de spécifications fonctionnelles et technique de l'access layer

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#57]
En tant que développeur, j'ai besoin des spécifications techniques sur comment accéder aux index de données.

#### Notes
D'un point de vue de notre système, comment va t-on stocker les données cliniques. (par exemple avec PGSQL, Song)
Dans quoi, comment et quand, ou stocker les données dans notre système. (et non pas desquels on extrait les données dans l'ETL)

Comment notre système va t-il accéder aux données qui sont stockées dans ses bases de données?

Nous avons choisi ElasticSearch (ES2) et GraphQL. (accessible depuis le backend)

#### Tâches
- définition des accès aux données (couche d'accès aux données)

#### Livrables
- Schéma d'indexation ES2
- Expliquer comment indexer song dans ES2

**Comment by latch2112** [comment]
https://github.com/cr-ste-justine/clin-project/wiki/ES
