### ISSUE TITLE
Rédaction de spécifications des stratégie de droits

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#58]
En tant que développeur, j'ai besoin d'un document expliquant les permissions de chaque groupe et rôle.

#### Livrables
- liste de de groupe et de rôles avec leurs permissions détaillées avec des règles-métier. 3 pages environ.
- tableau explicatif
- exemple de study et groupe et rôles, droits de lecture, download
- s'assurer côté légal.

**Comment by Emma-Drieux** [comment]
- [x] liste de de groupe et de rôles avec leurs permissions détaillées avec des règles-métier
    tableau explicatif : https://github.com/cr-ste-justine/clin-project/wiki/User-Management 
    section: Rôles
- [x] s'assurer côté légal: https://github.com/cr-ste-justine/clin-project/wiki/R%C3%A9glementation

**Comment by aalex** [comment]
SVP indiquer la bonne page wiki pour la stratégie de droits, et je pourrai fermer le ticket. @Emma-Drieux

**Comment by Emma-Drieux** [comment]
https://github.com/cr-ste-justine/clin-project/wiki/Sp%C3%A9cifications-des-strat%C3%A9gie-de-droits

**Comment by Emma-Drieux** [comment]
https://github.com/cr-ste-justine/clin-project/wiki/R%C3%A9glementation

**Comment by aalex** [comment]
- J'ai mis des :question: dans https://github.com/cr-ste-justine/clin-project/wiki/R%C3%A9glementation - aussi, je recommanderais que l'on renomme la page pour lui donner un titre plus évocateur du fait qu'il s'agit de règles qui ont trait au permissions des usagers. (ou est-ce bien ça?)
- Je crois qu'il faudrait un tableau plus simplifié dans la page https://github.com/cr-ste-justine/clin-project/wiki/Sp%C3%A9cifications-des-strat%C3%A9gie-de-droits - je recommanderais un tableau qui liste les permissions, (create, read, update, delete) selon qui a créé chaque item, ou si j'appartient au groupe auquel il est assigné ou pas.

**Comment by aalex** [comment]
LGTM. (looks good to me - ça veut dire que j'approuve ces changements)

Je me demande si @nyanofthemoon et @steptek vont trouver ces pages assez simples à comprendre pour effectuer leur travail, par contre.

**Comment by Emma-Drieux** [comment]
Faudra qu'ils regardent.. @steptek @nyanofthemoon des avis?

**Comment by aalex** [comment]
À modifier https://github.com/cr-ste-justine/clin-project/wiki/Sp%C3%A9cifications-des-strat%C3%A9gie-de-droits

- Page wiki: enlever ce qui est technique et qui a trait à Song et Score. Remplacer "laboraoire de sequencage" (sic) par "laboratoire de diagnostique". Le médecin-référent: sera pour une version future.

Prochaine étape:  Intégrer sous forme de règles dans les dans les specs techniques #56 et #57 (architecture design diagram ou entité-relation)
