### ISSUE TITLE
Rédaction de spécifications fonctionnelles de l'interface Web

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#59]
En tant que développeur, j'ai besoin des spécifications du UI Web.

#### Livrables
- [x] Liste des pages avec la liste de leur contenu.
- [x]  Description des liens entre les pages
- [x]  Expliquer les composantes (widgets) utilisées dans le UI

**Comment by aalex** [comment]
Ajouter une page get token.

**Comment by nyanofthemoon** [comment]
@Emma-Drieux @aalex Est-ce que je peux avoir le lien pour le wireframe svp?

**Comment by nyanofthemoon** [comment]
Description des liens entre les pages : https://github.com/cr-ste-justine/clin-project/wiki/Web-App-:-Functional-Specifications

**Comment by nyanofthemoon** [comment]
Liste des pages avec la liste de leur contenu : https://drive.google.com/drive/u/1/folders/1TN3N_akEddLrebytdxDlpbDlu2L_Y1p9

**Comment by nyanofthemoon** [comment]
Expliquer les composantes (widgets) utilisées dans le UI: https://github.com/cr-ste-justine/clin-project/wiki/Web-App-:-Technical-Specifications

**Comment by aalex** [comment]
@nyanofthemoon Puis-je avoir l'accès au fichier avec la liste des pages? (sur Google Drive)

**Comment by nyanofthemoon** [comment]
> @nyanofthemoon Puis-je avoir l'accès au fichier avec la liste des pages? (sur Google Drive)
https://drive.google.com/drive/u/1/folders/1TN3N_akEddLrebytdxDlpbDlu2L_Y1p9

**Comment by aalex** [comment]
Mon usager Google (pour le drive, entre autres) pour cette équipe est quessy.crsj@gmail.com

**Comment by aalex** [comment]
> > @nyanofthemoon Puis-je avoir l'accès au fichier avec la liste des pages? (sur Google Drive)
> > https://drive.google.com/drive/u/1/folders/1TN3N_akEddLrebytdxDlpbDlu2L_Y1p9

Je n'ai toujours pas accès à ce fichier.

**Comment by nyanofthemoon** [comment]
> > > @nyanofthemoon Puis-je avoir l'accès au fichier avec la liste des pages? (sur Google Drive)
> > > https://drive.google.com/drive/u/1/folders/1TN3N_akEddLrebytdxDlpbDlu2L_Y1p9
> 
> Je n'ai toujours pas accès à ce fichier.

Tu devrais avoir accès maintenant.

**Comment by aalex** [comment]
Ah! Il s'agit de la maquette, et non pas d'un nouveau document. Ok.
