### ISSUE TITLE
Définir comment gérer les identifiants

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#6]
Document expliquant quels sont les avantages et inconvénient de chaque système potentiel. On a des identifiants pour chaque entités. (document, échantillon, spécimen, donneur, clinicien, etc.)

Recherche et investigation sur la solution des indentifiants. Maintenir le système actuel (idcc-identifers) ou changer?

Critères d'acceptance
- page dans le wiki expliquant comment on gère les identifiants dans le système Clin.
- les identifiants de donneurs commencent par "PA"
- choisir les préfixes

**Comment by aalex** [comment]
SVP créer une page wiki avec le résultat de votre évaluation. https://github.com/cr-ste-justine/wiki/wiki/_new

**Comment by aalex** [comment]
SVP indiquer ici le lien vers la page avec les spécifications fonctionnelles produites, et je pourrai fermer ce ticket. @Emma-Drieux

**Comment by Emma-Drieux** [comment]
https://github.com/cr-ste-justine/clin-project/wiki/Gestion-des-identifiants

**Comment by aalex** [comment]
Il faudrait s'assurer que les UUID sont bien du format 110e8400-e29b-11d4-a716-446655440000 et l'indiquer, mais sinon, LGTM.

**Comment by aalex** [comment]
On ne changera pas les préfix des identifiants dans Song pour le MVP.
