### ISSUE TITLE
Recueillir les besoins de l'analyste génomique

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#61]
Nous avons besoin des spécifications du contenu de la page patient.

Tâches:
- Réviser le contenu de la page patient (après la rencontre avec Julie l'analyste généticienne)

Questions:
- quels sont les champs obligatoires que l'on demande à Virginie?
- Quels sont les besoins des usagers analystes généticiens?

Critères d'acceptance:
- créer une page wiki avec la liste des besoins des généticiens; 
- ainsi que le flots des activités de la réception du dossier au diagnostique

**Comment by Emma-Drieux** [comment]
Premiere rencontre prevue vendredi 15 mars de 12h45 a 14h

**Comment by aalex** [comment]
Le document de travail est ici: https://docs.google.com/document/d/1L1OGKwuKGxQ0t3_qzb5CRQpPMahAh03PHZcIzVQf6Is/edit

Le contenu pourra être déplacé dans le wiki une fois révisé.

**Comment by aalex** [comment]
J'ai créé la page suivante: 
https://github.com/cr-ste-justine/clin-project/wiki/%C3%89tapes-de-traitement-d'un-dossier

J'ai mis à jour la page suivante:
https://github.com/cr-ste-justine/clin-project/wiki/R%C3%A9cits-utilisateurs

**Comment by Emma-Drieux** [comment]
- Les champs obligatoires demandes a Virginie sont ceux des des json: 
https://github.com/cr-ste-justine/clin-etl/tree/dev/song_json_schemas
Donnees indispensables et absentes de la base de donnees de Virginie:
https://github.com/cr-ste-justine/clin-project/wiki/Implementation-de-Song-et-Score-pour-le-projet-Clin

![champs obligatoires](https://user-images.githubusercontent.com/12585875/54687695-8d058100-4af2-11e9-893b-3dd33c87fe4a.png)

- Les besoins des geneticiens: pour effectuer son analyse, le geneticien (ou analyste) a besoin:
   * Fichiers obtenus apres l'analyse bioinformatique: fichiers BAM et BAI du proband et ceux de sa famille (pour la visualisation avec IGV) et le rapport de variants
   * Les donnees cliniques du proband (obtenues notament sur Phenotips)
Les etapes realises actuellement au niveau du laboratoire de diagnostic comportent enormement de saisie manuelle. Le processus sera peut etre optimise dans le futur. Aussi, il est important de garder une trace dans le systeme informatique (=centraliser) dedie a l'analyse des variants (qui est en cours de developpement) des documents cumules au cours du processus comme: la demande d'analyse rempli a l'attention du laboratoire, la prescription du medecin, le resultat de l'analyse par SANGER ...
