### ISSUE TITLE
Connaître les instructions pour demander un nouveau mot de passe

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#63]
En tant qu'usager, je dois pouvoir savoir comment faire la demande du renouvellement de mon mot de passe auprès du coordonnateur.

Si un usager a oublié son mot de passe, il devra envoyer un courriel au coordonnateur du centre de séquençage.

## Critères d'acceptance 
- Cliquer sur j'ai oublié mon mot de passe devrait faire afficher un message disant d'écrire au coordonnateur du centre de séquençage.

Le texte est dans la page suivante: https://github.com/cr-ste-justine/clin-project/wiki/R%C3%A9initialiser-son-mot-de-passe

**Comment by steptek** [comment]
Configuration S.G.A pour le coordonnateur est faite, et ce dernier a un access on R.W sur le Realm ayant les utilisateurs (Usagers.)

**Comment by steptek** [comment]
https://github.com/cr-ste-justine/clin-project/wiki/S.G.A

**Comment by steptek** [comment]
l'UI affichera un pop-up indiquant comment demander un renouvellement.
