### ISSUE TITLE
Filtrer les résultats de recherche selon les permissions

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#64]
Analyser la possibilité de filtrer les résultats de recherche GraphQL selon les droits ACL.

# Critères d'acceptance
- Expliquer comment utiliser les ACL à travers GraphQL (filter les résultats afin que les usagers ne puissent voir que ce pour quoi ils sont autorisés)

**Comment by nyanofthemoon** [comment]
@aalex @latch2112 https://github.com/cr-ste-justine/clin-project/wiki/Clin-Proxy-Api-%3A-Technical-Specifications

**Comment by latch2112** [comment]
https://github.com/cr-ste-justine/clin-project/wiki/Clin-Proxy-Api%3A-Technology-Stack
