### ISSUE TITLE
Choix du framework web

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#7]
Document précisant quelles seront les technologies employées. (NodeJS, quelle base de données, React, quelle librairie de widgets pour React, quel thème Material, etc.)

Backend et frontend (e.g Material...)

**Comment by nyanofthemoon** [comment]
https://ant.design/docs/react/introduce

**Comment by aalex** [comment]
SVP créer une page wiki ey y mettre la liste des technologies dans la stack qui sera employée. :) 
https://github.com/cr-ste-justine/wiki/wiki/_new

**Comment by millette** [comment]
Salut @aalex,

Si vous voulez un truc React en JavaScript (browser/nodejs) avec _server-side rendering_ dynamique, je recommande https://github.com/zeit/next.js/

**Comment by aalex** [comment]
Merci @millette ! @nyanofthemoon le connaît, mais personne dans l'équipe n'est assez familier-ère avec, pour le moment. Nous allons regarder ça!

**Comment by millette** [comment]
Connait React, next.js ou Gatsby?

**Comment by aalex** [comment]
https://github.com/cr-ste-justine/wiki/wiki/CLIN-Frontend-Technology-Choices

**Comment by millette** [comment]
Salut @aalex - bon succès avec votre projet. Je comprends pas que mes messages soient disparus, je voulais juste donner un petit coup de pouce.
