### ISSUE TITLE
Spécifications du contenu et des fonctionalité des pages patient

### ISSUE THREAD

**Issue by aalex** [cr-ste-justine/clin-project#8]
Tableau décrivant chaque champ dans la fiche d'identification du patient, dans son analyse des variants, et dans ses données cliniques. Esquisse

Page Log, recherche/listes de patients, page patients, téléchargement. TODO: rencontrer virginie et rené pour specifier le contenu de ces pages. Liste de questions pour Virginie.

**Comment by aalex** [comment]
Peut-être séparer cette story en plusieurs:
- tableau décrivant chaque champ
- esquisse UX
- requis fonctionnels et user stories de cette page

**Comment by Emma-Drieux** [comment]
Lien drive:
https://drive.google.com/drive/folders/191njJS8G-QxRt2MJPr6cvBo2yqT0s7qS

**Comment by aalex** [comment]
LGTM. Merci!
