### ISSUE TITLE
[CLIN-VAR] Créer des SQON et sauvegarder ceux-ci par “Practitioner” et Organisation

### ISSUE THREAD

**Issue by Emma-Drieux** [cr-ste-justine/clin-project#91]
Storage method is ElasticSearch

Backend:
- [x] Create `MetaService` in `clin-proxy-api`
  - [x] acl per practitionerId and organizationId
  - [x] empty patientId is a default statement
  - [x] non-empty is a research statement
  - [x] use ElasticSearch REST API for CRUD
- [x] npm script in `package.json`

Devops:
- [x] Create Docker file
- [x] Create Docker compose file
- [x] Update deploy.sh
- [x] Update redeploy.sh
- [x] Configure `.env` file
- [x] `/statement/_doc`
- [x] `/statement/_search`
- [x] Schema:
```
uid
practitionerId
organizationId
patientId
  - if empty, it is a default statement
  - if not empty, it is a composite of queries from a default statement and a research statement
title
description
defaultQueries
researchQueries
```

**Comment by latch2112** [comment]
Backend service completed and tested...  Need to be integrated to UI components
