### ISSUE TITLE
[TI-CLIN] Home Page Integration

### ISSUE THREAD

**Issue by Emma-Drieux** [cr-ste-justine/clin-project#98]
Based on Lucas' design:

- [ ] Header section
- [ ] Navigation section
- [ ] Footer section
- [ ] Content section when logged out
- [ ] Content section when logged in by role

Roles are: `administrator`, `genetician` and `practitioner`.

**Comment by nyanofthemoon** [comment]
Blocked until the design is completed.

**Comment by nyanofthemoon** [comment]
@claudia1296 Please see with Lucas :)
